create an github artifact with the contents of /var/lib/crucible

diff --git a/run-ci b/run-ci
--- a/run-ci
+++ b/run-ci
@@ -83,18 +83,30 @@ for userenv in $(echo "${CI_USERENVS}" | sed -e "s/,/ /g"); do
     esac
 done
 
-set -e
+RC_STATUS=0
 
 function run_cmd {
-    local cmd
+    local cmd rc
     cmd=${1}
     shift
 
-    echo "Running: ${cmd}"
-    echo
-    ${cmd}
-    echo
-    echo
+    if [ ${RC_STATUS} == 0 ]; then
+        echo "Running: ${cmd}"
+        echo
+        ${cmd}
+        rc=${?}
+        echo "rc=${rc}"
+        echo
+        echo
+
+        if [ ${RC_STATUS} == 0 ]; then
+            RC_STATUS=${rc}
+        fi
+    else
+        echo "Skipping: ${cmd}"
+        echo
+        echo
+    fi
 }
 
 run_cmd "cat /etc/sysconfig/crucible"
@@ -137,3 +149,30 @@ run_cmd "podman ps --all --external"
 run_cmd "podman images"
 
 run_cmd "ls -laR /home/crucible-containers"
+
+if pushd /var/lib > /dev/null; then
+    if [ ! -d "crucible" ]; then
+        echo "ERROR: /var/lib/crucible does not exist for creating an artifact"
+        exit 1
+    fi
+
+    tarball="crucible-ci-artifact_$(uuidgen).tar"
+    echo "Creating ${tarball} from /var/lib/crucible"
+    if tar -cf ${tarball} crucible; then
+        echo "Compressing ${tarball} with xz"
+        if ! xz -v -T0 ${tarball}; then
+            echo "ERROR: Failed to xz compress ${tarball}"
+            exit 1
+        fi
+    else
+        echo "ERROR: Failed to create tar archive of /var/lib/crucible"
+        exit 1
+    fi
+
+    popd > /dev/null
+else
+    echo "ERROR: Could not pushd to /var/lib"
+    exit 1
+fi
+
+exit ${RC_STATUS}
