create shared validate_ci_clean_environment function in base script

diff --git a/.github/actions/integration-tests/base b/.github/actions/integration-tests/base
--- a/.github/actions/integration-tests/base
+++ b/.github/actions/integration-tests/base
@@ -31,6 +31,19 @@ function log_rc {
     fi
 }
 
+function validate_ci_clean_environment {
+    case "${CI_CLEAN_ENVIRONMENT}" in
+        yes|no)
+            echo "CI Clean Evironment is '${CI_CLEAN_ENVIRONMENT}'"
+            echo
+            ;;
+        *)
+            echo "ERROR: Unknown value for --clean-environment [${CI_CLEAN_ENVIRONMENT}].  Acceptable values are 'yes' and 'no'."
+            exit 1
+            ;;
+    esac
+}
+
 function validate_ci_run_environment {
     case "${CI_RUN_ENVIRONMENT}" in
         standalone|github)
