build and use the controller testing

diff --git a/.github/actions/integration-tests/base b/.github/actions/integration-tests/base
--- a/.github/actions/integration-tests/base
+++ b/.github/actions/integration-tests/base
@@ -31,6 +31,19 @@ function log_rc {
     fi
 }
 
+function validate_ci_build_controller {
+    case "${CI_BUILD_CONTROLLER}" in
+        yes|no)
+            echo "CI Build Controller is '${CI_BUILD_CONTROLLER}'"
+            echo
+            ;;
+        *)
+            echo "ERROR: Unknown CI_BUILD_CONTROLLER value [${CI_BUILD_CONTROLLER}]"
+            exit 1
+            ;;
+    esac
+}
+
 function validate_ci_clean_environment {
     case "${CI_CLEAN_ENVIRONMENT}" in
         yes|no)
