create a distinct github mode for github specific actions and output formatting

diff --git a/.github/actions/integration-tests/ci-environment-info b/.github/actions/integration-tests/ci-environment-info
--- a/.github/actions/integration-tests/ci-environment-info
+++ b/.github/actions/integration-tests/ci-environment-info
@@ -2,10 +2,60 @@
 # -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
 # vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
 
+SCRIPT_DIR=$(dirname $0)
+SCRIPT_DIR=$(readlink -e ${SCRIPT_DIR})
+
+. ${SCRIPT_DIR}/base
+
+CI_RUN_ENVIRONMENT="standalone"
+
+longopts="run-environment:"
+opts=$(getopt -q -o "" --longoptions "${longopts}" -n "$0" -- "$@")
+if [ ${?} -ne 0 ]; then
+    echo "ERROR: Unrecognized option specified: $@"
+    exit 1
+fi
+eval set -- "${opts}"
+while true; do
+    case "${1}" in
+        --run-environment)
+            shift
+            CI_RUN_ENVIRONMENT="${1}"
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "ERROR: Unexpected argument [${1}]"
+            shift
+            break
+            ;;
+    esac
+done
+
+case "${CI_RUN_ENVIRONMENT}" in
+    standalone|github)
+        echo "CI Run Environment is '${CI_RUN_ENVIRONMENT}'"
+        echo
+        ;;
+    *)
+        echo "ERROR: Unknown value for --run-environment [${CI_RUN_ENVIRONMENT}].  Acceptable values are 'standalone' and 'github'."
+        exit 1
+        ;;
+esac
+
 echo "CI Environment Information:"
 echo
+start_github_group "whoami"
 echo "whoami: $(whoami)"
+stop_github_group
 echo
+start_github_group "pwd"
 echo "pwd: $(pwd)"
+stop_github_group
 echo
+start_github_group "ls -la"
 echo -e "ls -la\n$(ls -la)"
+stop_github_group
